<?xml version='1.0' encoding='UTF-8'?> 
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version='1.0'>
  <dict>
    <key>name</key>
    <string>OnSave Console</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>comment</key>
        <string>CMD</string>
        <key>match</key>
        <string>^&gt;&gt;&gt; (#.*)$</string>
        <key>name</key>
        <string>storage</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.character</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>begin</key>
        <string>&quot;</string>
        <key>end</key>
        <string>&quot;</string>
        <key>name</key>
        <string>string.quoted.double.js</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>string.quoted.double.js</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>begin</key>
        <string>&apos;</string>
        <key>end</key>
        <string>&apos;</string>
        <key>name</key>
        <string>string.quoted.single.js</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.</string>
            <key>name</key>
            <string>string.quoted.single.js</string>
          </dict>
        </array>
      </dict>
      <dict>
        <key>comment</key>
        <string>esc</string>
        <key>match</key>
        <string>\\.</string>
        <key>name</key>
        <string>constant.character</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Symbol</string>
        <key>match</key>
        <string>[^\w:\.\[\]\(\)\;\,\{\}\/]</string>
        <key>name</key>
        <string>storage</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>File</string>
        <key>match</key>
        <string>(\/?(?:[\w\-\.]*?\/)+[\w\-\.]+\.\w+) *(?:\&quot; *|:|, *line|at *line){0,2} *(\d*)</string>
        <key>name</key>
        <string>string</string>
      </dict>
      <dict>
        <key>comment</key>
        <string>Number</string>
        <key>match</key>
        <string>(?&lt;![a-zA-Z])(0[xX][0-9a-fA-F]+|(?:\.\d+|\d+(?:\.\d+)?)(?:e\-?\d+)?)</string>
        <key>name</key>
        <string>constant.numeric</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>text.on-save</string>
    <key>uuid</key>
    <string>882bd578-e7a7-11e5-b2c6-600308a17fe2</string>
  </dict>
</plist>
